
name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unix:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: snickerbockers/submodules-init@v4
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: test
      run: make allTests